### ISSUE TITLE
Add Analytics Tracking to All Search 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#290]
### User story
Add analytics to track use of the all search. 

### Acceptance criteria

- [x] Confirm Analytics tracks basic web activity (page views, 
- [x] Confirm Analytics tracks the user's search queries
- [x] Confirm Analytics tracks events interactions with links
- [x] Confirm Analytics tracks interactions with form controls
- [ ] ~Confirm Analytics tracks the position of records users interact with~ Split out into #340
- [ ] ~Confirm Analytics tracks which trays the user engages in.~ Split out into #340
- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Implementation notes

We have added events to the catalog google analytics (GA4), look at that for an example.

**Comment by maxkadel** [comment]
@beth-german says we should use Google Analytics rather than Plausible for analytics

**Comment by maxkadel** [comment]
Need to wait 48 hours to start getting data. [analytics home for allsearch frontend](https://analytics.google.com/analytics/web/?authuser=0#/p447803729/reports/intelligenthome?params=_u..nav%3Dmaui)

**Comment by maxkadel** [comment]
Console errors on production:
```
allsearch.princeton.edu/:1 Refused to load the script 'https://www.googletagmanager.com/gtag/js?id=G-90G7R5LX2F' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
Understand this error
allsearch.princeton.edu/:11 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-g74TZuqXyEvAP6FdEpt+0JtpTgsdhGtaoBbtBJZwfXI='), or a nonce ('nonce-...') is required to enable inline execution.
```

**Comment by maxkadel** [comment]
Fix deployed to production midday Thursday, June 27, check for data on Monday.

**Comment by christinach** [comment]
@maxkadel  checked and we're not getting data

**Comment by maxkadel** [comment]
Getting basic data now. Enhanced data split out into ticket #340
