### ISSUE TITLE
Enhance Google Analytics Tracking

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/allsearch_frontend#340]
### User story
As User Experience professionals, we want to understand how tray position and result order affect user behavior - specifically clicks / selects through to resources. 

### Acceptance criteria
- [ ] Analytics tracks the position of records users interact with
- [ ] Analytics tracks which trays the user engages in
- [ ] Analytics tracks regardless of whether it is a click or key-press
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Concrete example
I can see whether the user clicked through on the first, second, or third result in the Catalog tray.

### Implementation notes, if any
- [Existing Analytics Dashboard](https://analytics.google.com/analytics/web/?authuser=0#/p447803729/reports/intelligenthome?params=_u..nav%3Dmaui)

**Comment by kevinreiss** [comment]
An expanded version of this ticket has been created https://github.com/pulibrary/allsearch_frontend/issues/538. All the acceptance criteria of this ticket is included there.
